### ISSUE TITLE
Seems that the interpreters for the maze and paint games are missing.

### ISSUE THREAD

**Issue by jimmyfly100** [imagicbell/ublocklygame#3]
I was trying to run game demos but there are no categories for maze and paint blocks. I checked carefully and the reason was likely to be the lack of interpreters. Would you please share them?

**Comment by imagicbell** [comment]
Hello Ruochen,

Thank you for trying out my work. The issue mostly is caused by Unity version. It is a very old work that I did and is not maintained anymore. Sorry for the troubles.
You could follow the instructions and fix all Unity errors to see if it works. Thanks!

Best Regards,
Ling

From: Ruochen TIAN ***@***.***>
Date: Tuesday, September 26, 2023 at 5:00 AM
To: imagicbell/ublocklygame ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [imagicbell/ublocklygame] Seems that the interpreters for the maze and paint games are missing. (Issue #3)

I was trying to run game demos but there are no categories for maze and paint blocks. I checked carefully and the reason was likely to be the lack of interpreters. Would you please share them?

**Comment by jimmyfly100** [comment]
Hi Ling,
Thanks for replying! I fixed the settings and now it works! Really a great work!
